<a href="https://colab.research.google.com/github/alexyev/pytorch_projects/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.tensor([5, 3])
y = torch.tensor([2, 1])

print(x * y)

tensor([10,  3])


In [ ]:
x = torch.zeros([2, 5])

In [ ]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
y = torch.rand([2, 5])

In [ ]:
y

tensor([[0.6552, 0.1009, 0.6215, 0.0814, 0.9487],
        [0.9857, 0.2550, 0.1919, 0.1704, 0.0145]])

In [ ]:
y.view([1, 10])

tensor([[0.6552, 0.1009, 0.6215, 0.0814, 0.9487, 0.9857, 0.2550, 0.1919, 0.1704,
         0.0145]])

In [ ]:
y

tensor([[0.6552, 0.1009, 0.6215, 0.0814, 0.9487],
        [0.9857, 0.2550, 0.1919, 0.1704, 0.0145]])